### PR TITLE
Translation & Setup Wizard

### PR DESCRIPTION
**Pull request by plun1331**
Implements a translation system as well as a setup wizard.

Server configuration has not been implemented, but it exists.

### CODE REVIEW

**Comment by MFDGaming** [comment]
@plun1331 The wizard is scuffed and the translation system lacks important stuff

**Comment by MFDGaming** [comment]
also it isnt following the snake case

**Comment by plun1331** [comment]
> @plun1331 The wizard is scuffed and the translation system lacks important stuff

what should be added to translation

**Comment by plun1331** [comment]
image

Converted to Spanish with google translate, the only problem was being unable to decode the contents, so I switched it to a different encoding.

**Pull request merged**
